version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(ci)"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nuget:
        patterns: ["*"]
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/src/MyWorkID.Client"
    schedule:
      interval: "weekly"
    groups:
      npm-client:
        patterns: ["*"]
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/deploy/web"
    schedule:
      interval: "weekly"
    groups:
      npm-deployment:
        patterns: ["*"]
    open-pull-requests-limit: 5
