name: 'Test CI'

on:
  pull_request:

permissions:
  contents: read
  checks: write
  
env:
  DOTNET_CORE_VERSION: 8.0.x

jobs:
  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Restore NuGet Cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('src/MyWorkID.Server') }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
      - name: Test
        run: |
          dotnet test --logger "trx;logfilename=testResults.trx"
      - name: Gather Test Results
        if: success() || failure()
        run: |
          mkdir TestResults
          cp tests/MyWorkID.Server.IntegrationTests/TestResults/testResults.trx TestResults/Integration-Tests.trx
          cp tests/MyWorkID.Server.UnitTests/TestResults/testResults.trx TestResults/Unit-Tests.trx
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: success() || failure()
        with:
          name: testResults
          path: TestResults/*.trx
