name: 'Test Report'
on:
  workflow_run:
    workflows: ['Test CI']
    types:
      - completed

permissions:
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: dorny/test-reporter@d1b5dff021aa968b288b02285a8bf47471c5928a # v3.2.0
      with:
        artifact: testResults
        name: test report
        path: '*.trx'
        reporter: dotnet-trx
        use-actions-summary: 'false' # Write summary into check run details instead of actions summary
